### ISSUE TITLE
Break DDG

### ISSUE THREAD

**Issue by Schanzation** [ansul1001/Ansul-s-Ad-Filters#1]
Hello! Whenever I am using this script I cannot use duckduckgo.com in Firefox . It just uses the HTML site. Whenever I disable ansul in ublock-origin, duckduckgo works like normal again.

**Comment by TechnoFairyGirl** [comment]
I can't reproduce this on my phone. I'm using a desktop UA, Ansul's list is enabled, and Facebook blocking is working, so it should be representative of a desktop experience. But I'll try it on my PC later tonight.

I'm using FF on my phone. I'll try both FF and Chrome when I test it later.

**Comment by Schanzation** [comment]
Ok. I have not tested it on my phone. I use desktop computer. Windows 10

**Comment by Schanzation** [comment]
Still having this issue :<

**Comment by ansul1001** [comment]
I have tried to replicate the problem on Firefox Version 74.0 several time and it works every time
