### ISSUE TITLE
Non-ad content being blocked

### ISSUE THREAD

**Issue by anghelos** [ansul1001/Ansul-s-Ad-Filters#2]
Hi there!

Since a week or two, many non-ad posts are being blocked. Notably, when clicking on a notification that links to a single post (belonging to a business page), the post itself is blocked.

It's caught by the following filter:
facebook.com##div[id^=hyperfeed_story_id_]:has(a[role^=button]:has(:scope > span:has-text(S)):not(:has-text(1)):not(:has-text(2)):not(:has-text(3)):not(:has-text(4)):not(:has-text(5)):not(:has-text(6)):not(:has-text(7)):not(:has-text(8)):not(span:has-text(9)):not(span:has-text(w)))

**Comment by anghelos** [comment]
I also notice multiple non-ad posts disappearing in my feed (they appear shortly).

**Comment by ansul1001** [comment]
I have tried several times and I cannot duplicate it

**Comment by anghelos** [comment]
I believe it might be because I'm the owner of the page.
My Facebook has been updated to the new look, so this isn't really relevant anymore (none of the old filters seem to work)... Thanks for looking into it!
